/**:
  ros__parameters:
    x0: 0.0 # m, robot
    y0: 0.0 # m, robot
    z0: 0.0 # m, robot
    theta0: 0.0 # rad, robot heading
    x_length: 2.0 # m, length of arena in x-dir
    y_length: 2.0 # m, length of arena in y-dir
    obstacles:
      x: [-0.6, 0.7, 0.5] # x-coordinates of obstacles
      y: [-0.8, -0.7, 0.9] # y-coordinates of obstacles
      r: 0.038 # m
